pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                dir("${workspace}/$pipeline-yml/Calculadora"){
                    sh "pwd"
                }
                sh './gradlew check'
            }
        }
    }
    post {
        always {
            junit 'build/reports/**/*.xml'
        }
    }
}