pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                sh 'gradle test --tests=OperacionTest'
            }
        }
    }
    post {
        always {
            junit 'build/reports/**/*.xml'
        }
    }
}