pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                sh './gradlew clean build'
            }
        }
    }
    post {
        always {
            junit 'build/reports/tests/test/*.html'
        }
    }
}